// <auto-generated />
namespace Small2.WebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201407131448194_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
